#!/usr/bin/env python

import sys

import click
import sh

if sh.which('nmpvc') is None:
    click.echo("ERROR: missing nmpvc clinet", err=True)
    sys.exit(1)


print(sh.nmpvc.smb(*(
    '--credentials rpi-server MyNAS alarm nincompoop '
    '--path /videos/music/ '
    "search -m 2 -s write '.*' "
    'append --server pi-bed'
).split()))
