#!/usr/bin/env python
""" Just a starter """

import os

import eel  # type: ignore


eel_path = os.path.abspath(__file__).rsplit('/', 1)[0] + '/web'

eel.init(eel_path)
eel.start(
    'index.html',
    mode='chrome-app',
    port=0
)
